server:
  port: 8080

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/TrashMarket
    username: postgres
    password: 777
  liquibase:
    change-log: liquibase/master.xml
hibernate:
  jdbc:
    use_streams_for_binary: false
